project_id = "lpgyafvuihdymgsrmswh"

[functions.generate-website]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.fetch-images]
verify_jwt = false

[functions.check-subdomain]
verify_jwt = false

[functions.wizard-chat]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.regenerate-content]
verify_jwt = false

[functions.fetch-image-options]
verify_jwt = false

[functions.add-custom-domain]
verify_jwt = false

[functions.verify-domain]
verify_jwt = false

[functions.remove-domain]
verify_jwt = false

[functions.studio-generate-image]
verify_jwt = false

[functions.chai-ai-assistant]
verify_jwt = false
