project_id = "lpgyafvuihdymgsrmswh"

[functions.generate-website]
verify_jwt = false

[functions.generate-images]
verify_jwt = false

[functions.fetch-images]
verify_jwt = false

[functions.check-subdomain]
verify_jwt = false

[functions.wizard-chat]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.regenerate-content]
verify_jwt = false

[functions.fetch-image-options]
verify_jwt = false
